plugins {
    id("convention.kotlin-android-library")
    id("convention.publish-android-library")
    id("convention.libraries")
}

dependencies {
    implementation(projects.common.okhttp)
    implementation(projects.common.httpClient)
    implementation(projects.common.time)
    implementation(projects.common.fileStorage)
    implementation(projects.common.reportViewer)
    implementation(projects.common.logger)
    implementation(projects.common.elasticLogger)
    implementation(projects.common.sentry)
    implementation(projects.common.result)
    implementation(projects.common.testAnnotations)
    implementation(projects.common.throwableUtils)
    implementation(projects.androidTest.androidLog)
    implementation(projects.androidTest.uiTestingCore)
    implementation(projects.androidTest.resourceManagerExceptions)
    implementation(projects.androidTest.websocketReporter)
    implementation(libs.okio)
    implementation(libs.kotson)
    implementation(libs.okhttp)
    implementation(libs.radiography)

    testImplementation(libs.jsonPathAssert)
    testImplementation(libs.mockitoKotlin)
    testImplementation(libs.okhttpMock)
    testImplementation(projects.common.junitUtils)
    testImplementation(projects.common.resources)
    testImplementation(projects.common.truthExtensions)
    testImplementation(testFixtures(projects.common.logger))
    testImplementation(testFixtures(projects.common.time))
    testImplementation(testFixtures(projects.common.httpClient))
}
