plugins {
    id("convention.kotlin-jvm")
    id("convention.kotlin-serialization")
}

dependencies {
    implementation(project(":subprojects:common:teamcity-common"))
    implementation(libs.kotlinXCli)
    implementation(project(":subprojects:common:graphite"))
    implementation(project(":subprojects:common:result"))

    implementation(project(":subprojects:gradle:clickstream"))
    implementation(project(":subprojects:gradle:bitbucket"))

    testImplementation(libs.okhttpMockWebServer)
}

tasks.register("sendTeamcityBuildsMetrics", JavaExec) {
    mainClass = "com.avito.teamcity.SendTeamcityBuildsMetricsMain"
    classpath = sourceSets.getByName(SourceSet.MAIN_SOURCE_SET_NAME).runtimeClasspath

    args(
        "sendMetrics",
        "--teamcityUrl", project.providers.gradleProperty("teamcityUrl").getOrNull(),
        "--teamcityApiUser", project.providers.gradleProperty("teamcityApiUser").getOrNull(),
        "--teamcityApiPassword", project.providers.gradleProperty("teamcityApiPassword").getOrNull(),
        "--metricsSourcesConfigPath", project.providers.gradleProperty("metricsSourcesConfigPath").getOrNull(),
        "--graphiteHost", project.providers.gradleProperty("graphite.host").getOrNull(),
        "--graphitePort", project.providers.gradleProperty("graphite.port").getOrNull(),
        "--metricsPrefix", project.providers.gradleProperty("buildMetrics.prefix").getOrNull(),
        "--clickstreamServiceUrl", project.providers.gradleProperty("clickstream.url").getOrNull(),
        "--bitbucketUrl", project.providers.gradleProperty("bitbucket.url").getOrNull(),
        "--bitbucketToken", project.providers.gradleProperty("bitbucket.token").getOrNull(),
    )
}

