package com.avito.android

import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec

/**
 * Generates compile-time constants with team uuids.
 *
 * Annotation arguments must be compile-time constants, so an enum entry of [com.avito.android.model.Team]
 * can't be passed to them directly.
 */
internal class CommandUuidsGenerator {

    fun generate(teams: List<ResolvedTeam>): FileSpec {
        val commandUuids = TypeSpec.objectBuilder(CLASS_NAME)
            .addKdoc(COMMENT)
            .apply {
                teams
                    .filter { team -> team.normalizedName.isValidConstantName() }
                    // Constant names are not guaranteed to be unique, and kotlinpoet keeps
                    // the last enum constant of the same name. Keep the same choice here,
                    // otherwise Owners and CommandUuids would point at different teams.
                    .associate { team -> team.normalizedName to team.owner.id }
                    .toSortedMap()
                    .forEach { (normalizedName, uuid) ->
                        addProperty(
                            PropertySpec.builder(normalizedName, String::class, KModifier.PUBLIC, KModifier.CONST)
                                .initializer("%S", uuid)
                                .build()
                        )
                    }
            }
            .build()

        return FileSpec.builder(PACKAGE, CLASS_NAME)
            .indent("    ")
            .addType(commandUuids)
            .build()
    }

    private fun String.isValidConstantName(): Boolean = isNotEmpty() && any { char -> char != '_' }

    internal companion object {
        const val PACKAGE = "com.avito.android.ownership"
        const val CLASS_NAME = "CommandUuids"

        val COMMENT = """
            !!! This file is autogenerated. Do not modify it by hands. !!!

            Use `./gradlew generateCodeOwnersFile` command to update the uuids.
            Constants are generated for teams only, units are not included.
        """.trimIndent()
    }
}
