#!/usr/bin/env bash

# Based on https://gohugo.io/hosting-and-deployment/hosting-on-github/

set -euf -o pipefail

git config --global core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
git config --global user.name "$GITHUB_GIT_USER_NAME";
git config --global user.email "$GITHUB_GIT_USER_EMAIL";
mkdir -p "${HOME}"/.ssh

removeGeneratedFiles() {
    rm -rf public
    git worktree prune
    rm -rf .git/worktrees/public/
}

echo "Deleting old generated files..."
removeGeneratedFiles

echo "Checking out gh-pages branch into public/ directory..."
git worktree add -B gh-pages public origin/gh-pages

echo "Generating site..."
cd docs/
# Don't cleanDestinationDir to preserve .git inside worktree
hugo --minify --theme book
cd ..

# TODO: use machine github user
echo "Updating gh-pages branch..."
cd public
touch README.md
echo "These file are auto-generated by hugo. See docs/publish" > README.md
# Amend history because we don't want to store a huge history of generated files
git add --all && git commit --amend -m "auto-generated files" && git push --force-with-lease

echo "Deleting generated files..."
removeGeneratedFiles
