#!/usr/bin/env sh

# Based on https://gohugo.io/hosting-and-deployment/hosting-on-github/

set -euf -o

git config --global core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
git config --global user.name "$GITHUB_GIT_USER_NAME";
git config --global user.email "$GITHUB_GIT_USER_EMAIL";
mkdir -p "${HOME}"/.ssh

removeGhPagesWorktree() {
    rm -rf public
    git worktree prune
    rm -rf .git/worktrees/public/
}

echo "Delete old worktree..."
removeGhPagesWorktree

echo "Check out gh-pages branch into public/ directory..."
git worktree add -B gh-pages public origin/gh-pages

echo "Generate site..."
hugo --cleanDestinationDir --minify --theme book --source docs

echo "Update gh-pages branch..."
cd public

echo "Remove previously generated files..."
git rm -r -- *
echo "Replace generated files..."
cp -RT ../docs/public .

touch README.md
echo "These file are auto-generated by hugo. See docs/publish" > README.md

git add --all
git status

echo "Push changes..."
# Amend history because we don't want to store a huge history of generated files
git commit --amend -m "auto-generated files" && git push --force-with-lease

echo "Deleting generated files..."
removeGhPagesWorktree
